Translate TomerGabel_2.md
scalajp/2017.scalamatsuri.org pull request #142
Opened 2016-11-01 17:13 UTC by Keita-N

2016-11-03 16:36 UTC, okapies commented on _candidates_ja/TomerGabel_2.md
> +title: "Functional Leap of Faith"　<- TBD
「関数型への賭け」とか？

2016-11-03 17:31 UTC, Keita-N commented on _candidates_ja/TomerGabel_2.md
> +title: "Functional Leap of Faith"　<- TBD
「関数型に飛び込む」がいいかなと思えてきました。
(元ネタ) http://oshiete.goo.ne.jp/qa/715202.html?from=rfqa_no

2016-11-03 18:47 UTC, eed3si9n requested changes

2016-11-03 18:47 UTC, eed3si9n commented on _candidates_ja/TomerGabel_2.md
> +title: "Functional Leap of Faith"　<- TBD
Leap of faith を賭け事に例えるのは意味が変わってきますね。
日本的なイメージだと「清水の舞台から飛ぶつもりの関数型」とか。

2016-11-06 02:24 UTC, okapies commented on _candidates_ja/TomerGabel_2.md
> +title: "Functional Leap of Faith"　<- TBD
あ、いいですね。なんかうまい言い回しないかなと思ってたので…。

2016-11-06 10:56 UTC, Keita-N commented on _candidates_ja/TomerGabel_2.md
> +title: "Functional Leap of Faith"　<- TBD
「清水の~」まで意訳する勇気がでなかったので、「関数型に飛び込む」でいいですか？

2016-11-06 15:40 UTC, okapies commented on _candidates_ja/TomerGabel_2.md
> +title: "Functional Leap of Faith"　<- TBD
@Keita-N それだとちょっとご提示のリンク先のニュアンスから遠ざかっている気がするので、「関数型に身を委ねる」とかですかねぇ。

2016-11-06 19:44 UTC, eed3si9n commented on _candidates_ja/TomerGabel_2.md
> +title: "Functional Leap of Faith"　<- TBD
日本語の「飛び込む」だけだとポジティブなニュアンスが無いので、「清水の舞台から飛ぶつもりの関数型」がダメなら「関数型へジャンプ! ☆」みたいな感じでしょうか。

2016-11-07 02:37 UTC, Keita-N commented on _candidates_ja/TomerGabel_2.md
> +title: "Functional Leap of Faith"　<- TBD
@eed3si9n 訳案が面白いですねw 「関数型へジャンプ!☆」頂きます。

2016-11-07 04:50 UTC, eed3si9n approved these changes

2016-11-07 04:50 UTC, merged