Translate MichaelCohen_2.md
scalajp/2017.scalamatsuri.org pull request #165
Opened 2016-11-06 11:54 UTC by Keita-N

fixes: #149

2016-11-06 20:40 UTC, eed3si9n requested changes
訳案を提示しました。

2016-11-06 20:40 UTC, eed3si9n commented on _candidates_ja/MichaelCohen_2.md
> +ソフトウェア・エンジニアリングは音楽や視覚芸術と同様にアートといえるものです。どちらにおいても、「正しい手法」というものはなく、しかし「間違った手法」は事実として存在します。
原文: Software Engineering is like Art (music / visual arts) in that they are the only two areas of human study that do not have a "correct way" of doing things, but in fact, do have "wrong ways" of doing things.

訳案: 研究分野が数多にある中で、「正しい方法」は無くても「間違った方法」はあるという分野は、ソフトウェア・エンジニアリングと芸術 (音楽や視覚芸術など) の 2つだけです。そういう意味で、ソフトウェア・エンジニアリングには芸術的な側面があると言えるでしょう。

2016-11-06 20:40 UTC, eed3si9n commented on _candidates_ja/MichaelCohen_2.md
> +芸術には多くの役割があり、ソフトウェア・エンジニアリングにおいても同様です。２つ間の類似を見て、どんな場面で、どのようにあなたはうまくやれるか理解しましょう。
原文: There are many different roles within art as there are within software engineering - see the parallels between the two and understand where/how you fit in.

訳案: 一言で芸術と言っても、その分野の中には様々な役職があり、もちろんそれはソフトウェア・エンジニアリングも同様です。この2つの分野を比較して、皆さんがどういう役割を果たしているのかを理解できればいいと思います。

2016-11-06 20:40 UTC, eed3si9n commented on _candidates_ja/MichaelCohen_2.md
> +芸術には美しさがあります。ソフトウェア・エンジニアリングにおいても美しさがあります。このトークでは、芸術を美たらしめているものは何か？ そして、ソフトウェア開発において、美しいコードを書くためにどうすれば同じ戦略を適用できるのか掘り下げていきます。
原文: There is beauty in art, as there is beauty in software engineering - this talk delves into what makes art beautiful, and how software engineers can employ the same tactics to make their code beautiful.

訳案: 芸術に美しさがあるように、ソフトウェア・エンジニアリングにおいても美しさがあります。このトークでは、芸術を美たらしめているものは何か？ そして、ソフトウェア開発において同じ戦略を適用して美しいコードを書けるのかどうかを掘り下げていきます。

2016-11-08 22:34 UTC, Keita-N commented
全面的に頂きます。ありがとうございます。

2016-11-09 01:29 UTC, eed3si9n approved these changes

2016-11-09 01:29 UTC, merged