translate JonPretty_1.md
scalajp/2017.scalamatsuri.org pull request #166
Opened 2016-11-06 15:31 UTC by okapies

fix #143

2016-11-06 19:56 UTC, eed3si9n requested changes

2016-11-06 19:56 UTC, eed3si9n commented on _candidates_ja/JonPretty_1.md
> +title: "鬼のように文字列補間する"
"like a baus (boss)" の感覚としては、やったことが凄すぎてその場でボス扱いという雰囲気なので、「オニのように眠る」みたいな局面だと「オニのように」が使えるかもしれませんが、"boss level" と続く今回には使えない気がします。
ニュアンスとして近いのは「ドヤ顔の文字列補間」なんですが、"boss level" につなげるためには「文字補間のラスボス」と Boss を敢えて活かすのがいいかなと思います。

2016-11-06 20:00 UTC, eed3si9n commented on _candidates_ja/JonPretty_1.md
> +この発表は四つの難易度（値レベル、型レベル、マクロレベル、鬼レベル）からなり、このようにすることで、初心者から上級者まですべてのユーザが新しいことを学べるだろう！
「ラスボス」レベル

2016-11-08 15:39 UTC, okapies commented on _candidates_ja/JonPretty_1.md
> +title: "鬼のように文字列補間する"
「ドヤ顔」もインパクト的に捨てがたいので、文中の表現とあえて合わせない方向にしてみます。

2016-11-08 15:40 UTC, eed3si9n approved these changes

2016-11-08 15:44 UTC, merged