Add docker compose
scalajp/2017.scalamatsuri.org pull request #267
Opened 2016-11-19 06:23 UTC by grimrose

dockerを使ってjekyllを使えるようにしてみました。

`docker-compose up` でjekyllがwatch modeで立ち上がります。

2016-11-21 07:53 UTC, tkawachi requested changes

2016-11-21 07:53 UTC, tkawachi commented on js/cfp-tag.coffee
> +
`*.coffee` を Jekyll にコンパイルしてもらうために `---` の行 (front matter) は必要です。

2016-11-21 14:41 UTC, grimrose commented on js/cfp-tag.coffee
> +
ここでエラーが出てたのですが、どうしたらいいですかね？

2016-11-21 14:50 UTC, tkawachi commented on js/cfp-tag.coffee
> +
あら、どんなエラーでした？

2016-11-21 14:53 UTC, grimrose commented on js/cfp-tag.coffee
> +
```
jekyll_1  |   Conversion error: Jekyll::Converters::CoffeeScript encountered an error while converting 'js/cfp-tag.coffee':
```

こんな感じです。

2016-11-21 14:55 UTC, grimrose commented on js/cfp-tag.coffee
> +
確かに、coffeeからコンパイルされなくて`ERROR `/js/cfp-tag.js' not found.`ってログが出てますね。

2016-11-21 15:01 UTC, tkawachi commented on js/cfp-tag.coffee
> +
なぜだろう…

2016-11-21 19:43 UTC, grimrose commented on js/cfp-tag.coffee
> +
docker imageが古かったので、公式のイメージを使いつつ、更新されていたモジュールを追加しました。

2016-11-22 12:45 UTC, tkawachi approved these changes
LGTM

2016-11-22 12:46 UTC, merged