Update index.html
scalajp/2017.scalamatsuri.org pull request #459
Opened 2017-02-27 10:30 UTC by grimrose

開催御礼のメッセージを表示するように変更。

2017-02-27 11:37 UTC, yohei1126 commented
英語の方のHTMLも修正していただくことは可能でしょうか？

ScalaMatsuri 2016 is successfully over with great contributions from participants, sponsors and staffs.  Thank you for making ScalaMatsuri a great conference!

2017-02-28 01:14 UTC, eed3si9n requested changes
こんな感じですかね

2017-02-28 01:14 UTC, eed3si9n commented on index_en.html
> +					<p>ScalaMatsuri 2016 is successfully over with great contributions from participants, sponsors and staffs.</p>
訳案: ScalaMatsuri 2016 came out to be another successful one thanks in many parts to sponsors, speakers,  staffs, and your attendance!

2017-02-28 01:14 UTC, eed3si9n commented on index_en.html
> +					<p>Thank you for making ScalaMatsuri a great conference!</p>
訳案: We owe you great gratitude, and we hope to see you again next year.

2017-02-28 01:17 UTC, eed3si9n commented on index_en.html
> +					<p>ScalaMatsuri 2016 is successfully over with great contributions from participants, sponsors and staffs.</p>
とりあえず "ScalaMatsuri 2016" ではないですね。

2017-02-28 04:48 UTC, yohei1126 commented
提案いただいた方が自然な英文ですので、採用をお願いします。すいませんが、修正もお願いします。

2017-02-28 19:26 UTC, eed3si9n approved these changes

2017-02-28 19:26 UTC, merged