Translate MichalMatloka_3.md
scalajp/2017.scalamatsuri.org pull request #94
Opened 2016-10-19 14:32 UTC by okapies

Fix #57

2016-10-19 14:47 UTC, eed3si9n requested changes

2016-10-19 14:47 UTC, eed3si9n commented on _candidates_ja/MichalMatloka_3.md
> +若い父親のちょっとした物語を通じて、親としてのあり方とソフトウェア開発のアナロジーについて話します。
原文: A quick story from a young father about analogies between parenthood and software development.
訳案: ヤングパパによる、親としてのあり方とソフトウェア開発のアナロジーについての小咄。

「若い父親」だと自分の父親の話と曖昧じゃないでしょうか。

2016-10-19 14:49 UTC, tkawachi requested changes

2016-10-19 14:49 UTC, tkawachi commented on _candidates_ja/MichalMatloka_3.md
> +title: "What can a programmer learn from having children?"
英語タイトルを残ってます

2016-10-19 14:54 UTC, tkawachi approved these changes

2016-10-19 15:24 UTC, okapies commented on _candidates_ja/MichalMatloka_3.md
> +若い父親のちょっとした物語を通じて、親としてのあり方とソフトウェア開発のアナロジーについて話します。
「ある年若い父親による」とかでどうでしょ。

2016-10-19 15:26 UTC, okapies commented on _candidates_ja/MichalMatloka_3.md
> +title: "What can a programmer learn from having children?"
対応ありがとうございます。

2016-10-19 16:05 UTC, NoriakiHoriuchi commented on _candidates_ja/MichalMatloka_3.md
> +若い父親のちょっとした物語を通じて、親としてのあり方とソフトウェア開発のアナロジーについて話します。
案）新米パパ

2016-10-19 16:08 UTC, eed3si9n commented on _candidates_ja/MichalMatloka_3.md
> +若い父親のちょっとした物語を通じて、親としてのあり方とソフトウェア開発のアナロジーについて話します。
自分で自分のことを「ある年若い父親」っていうのは日本語的に不自然な気がします。新米パパは良いと思います。

2016-10-19 16:11 UTC, eed3si9n commented on _candidates_ja/MichalMatloka_3.md
> +若い父親のちょっとした物語を通じて、親としてのあり方とソフトウェア開発のアナロジーについて話します。
あと原文には「〜を通じて〜話します」っていうのは無いと思いますがどうでしょうか。

2016-10-19 16:31 UTC, okapies commented on _candidates_ja/MichalMatloka_3.md
> +若い父親のちょっとした物語を通じて、親としてのあり方とソフトウェア開発のアナロジーについて話します。
新米パパいいですね、それで。構文は直します。

2016-10-20 20:13 UTC, eed3si9n approved these changes

2016-10-20 20:13 UTC, merged