Translate Yoshida_1.md
scalajp/2017.scalamatsuri.org pull request #96
Opened 2016-10-19 16:26 UTC by okapies

Fix #91
/review @smroy

2016-10-19 23:48 UTC, smroy commented on _candidates_en/Yoshida_1.md
> +ScalikeJDBC is a powerful and flexible DB access library. In combination with Skinny ORM, we can create a better relationship with the database. I'll introduce a case-study utilizing SQL to tackle th
Line 1: Should "DB" be written out as "data base"?
Line 2: What is "database" - does this need to be more specific?
Line 2: Again, should "database" be specific?
Line 2: "friendly" does not make sense in this context, but I don't know the subject area well enough to make an inference as to how I should edit this.
Line 3: Is "one year work experience" referring to one year running this program?

2016-10-19 23:48 UTC, smroy requested changes
Line 1: Should "DB" be written out as "data base"?
Line 2: What is "database" - does this need to be more specific?
Line 2: Again, should "database" be specific?
Line 2: "friendly" does not make sense in this context, but I don't know the subject area well enough to make an inference as to how I should edit this.
Line 3: Is "one year work experience" referring to one year running this program?

2016-10-20 20:32 UTC, eed3si9n commented on _candidates_en/Yoshida_1.md
> +ScalikeJDBC is a powerful and flexible DB access library. In combination with Skinny ORM, we can create a better relationship with the database. I'll introduce a case-study utilizing SQL to tackle th
> Line 1: Should "DB" be written out as "data base"?

Yes, but as one word _database_. In general though we can assume that the audience knows what a database is and does. I think the question is _a_ vs _the_. It's not like _the_ fridge where we can assume that everyone has one in their kitchen. So it's more like _a_ database in my opinion.

> Line 2: What is "database" - does this need to be more specific?

How about: In conjunction with Skinny ORM, it provides better handle to dealing with databases.

> Line 2: "friendly" does not make sense in this context, but I don't know the subject area well enough to make an inference as to how I should edit this.

> Line 3: Is "one year work experience" referring to one year running this program?

How about: I'll share my experience of using them in production for a year: SQL provides more direct access to the database, whereas the CRUD API provides easier to use wrapper around the database.

2016-10-20 23:49 UTC, smroy reviewed
I've made a few edits based on your comments; if this looks ok to you I will go ahead and approve. Thanks.

2016-10-21 00:47 UTC, eed3si9n approved these changes

2016-10-21 00:49 UTC, eed3si9n commented
Yea, I think it looks close enough to the Japanese original, which was written in somewhat vague way.

2016-10-21 00:49 UTC, merged

2016-10-21 11:54 UTC, grimrose commented
thanks 👍

2016-10-21 16:46 UTC, okapies commented
@smroy: Thanks for reviewing!

2016-10-22 00:01 UTC, smroy commented
@okapies Of course! I hope it was helpful.